---
title: "Wild Git Collaboration Practice"
format: 
  html:
    code-fold: show
execute: 
  warning: false
  message: false
---


## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)
library(ggplot2)

ggplot(diamonds) + 
  geom_point(aes(x=price, y=carat)) +
  theme_minimal()


```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"

# test
# test

```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```

